package mentalHealth;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * userSaveData is a back-end class tasked to save userData objects to an array which is then stored on a text file.
 * 
 * @author clayL and tylerR
 * @version 1.2
 *
 */
public class userSaveData {
	
	/**
	 * The 2D array which data is stored in, with rows indicating months, and columns indicating days.
	 */
	private userData [][] dataArray = new userData[12][31];
	
	/**
	 * The array in String form which is stored into a text file.
	 */
	private static String outputText;
	
	/**
	 * Takes in the userData that will be stored in the Array generated by this function.
	 * 
	 * @param segment userData segment to be inserted into the array.
	 */
	public void saveUserData(userData segment) {
		int segDay = segment.getDay()-1;
		int segMonth = segment.getMonth()-1;
		dataArray[segMonth][segDay]=segment;

		for (int i=0; i < dataArray.length; i++) {
			for (int j=0; i < dataArray[0].length; j++) {
				if(dataArray[i][j] != null) {
					outputText = dataArray[i][j].getRating() + "|" + dataArray[i][j].getNotes() + "|" + dataArray[i][j].getDay() + "|" + dataArray[i][j].getMonth() + "|" + dataArray[i][j].getLocaldate();
				}
			}
		}		

	}
	
	/**
	 * saveToFile takes the string generated from the array and saves it to a text file.
	 * 
	 * @throws IOException In case of IO failure.
	 */
	
	public static void saveToFile() throws IOException {
		saveFile("dataList.txt", outputText, true);
	}
	
	/**
	 * saveFile is a static function that saves a string to a file.
	 * 
	 * @param name The name of the file.
	 * @param text The string that will be saved.
	 * @param append Appends data.
	 * @throws IOException Thrown when improperly used.
	 */
	
	public static void saveFile(String name, String text, boolean append) throws IOException{
		File file1 = new File(name);

		FileWriter fw = new FileWriter(file1, append);

		PrintWriter pw = new PrintWriter(fw);

		pw.println(text);

		pw.close();
	}

}
