package mentalHealth;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * userSaveData is a back-end class tasked to save userData objects to an array which is then stored on a text file.
 * 
 * @author clayL and tylerR
 * @version 1.1
 *
 */
public class userSaveData {
	
	/**
	 * The array which data is stored in.
	 */
	private userData [] dataArray = new userData[365];
	
	/**
	 * The array in String form which is stored into a text file.
	 */
	private static String outputText;
	
	/**
	 * Takes in the userData that will be stored in the Array generated by this function.
	 * 
	 * @param segment userData segment to be inserted into the array.
	 */
	public void saveUserData(userData segment) {
		int segDate = segment.getDate()-1;
		dataArray[segDate]=segment;

		for (int i=0; i< dataArray.length; i++) {
			if(dataArray[i] != null) {
			outputText = dataArray[i].getRating() + "|" + dataArray[i].getNotes() + "|" + dataArray[i].getDate();
			}
		}		

	}
	
	/**
	 * saveToFile takes the string generated from the array and saves it to a text file.
	 * 
	 * @throws IOException In case of IO failure.
	 */
	
	public static void saveToFile() throws IOException {
		saveFile("dataList.txt", outputText, true);
	}
	
	/**
	 * saveFile is a static function that saves a string to a file.
	 * 
	 * @param name The name of the file.
	 * @param text The string that will be saved.
	 * @param append Appends data.
	 * @throws IOException Thrown when improperly used.
	 */
	
	public static void saveFile(String name, String text, boolean append) throws IOException{
		File file1 = new File(name);

		FileWriter fw = new FileWriter(file1, append);

		PrintWriter pw = new PrintWriter(fw);

		pw.println(text);

		pw.close();
	}

}
